package taskService;

/**
 * Task class for Java 1.8 compatibility.
 *
 * Stores information for a single task including:
 *  - Task ID (unique, immutable)
 *  - Name
 *  - Description
 *
 * The task ID is generated by TaskService and cannot be changed after creation.
 * All fields are immutable and final.
 */
public final class Task {
    private final String id;
    private final String name;
    private final String description;

    /**
     * Constructor for Task.
     *
     * @param id the unique task identifier
     * @param name the task name
     * @param description the task description
     */
    public Task(String id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    /**
     * Returns the task ID.
     *
     * @return the task ID
     */
    public String getID() {
        return id;
    }

    /**
     * Returns the task name.
     *
     * @return the task name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the task description.
     *
     * @return the task description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Compares this task with another object for equality.
     * Two tasks are equal if all their fields are equal.
     *
     * @param obj the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object obj) {
        // If comparator is null, default to false
        if (obj == null)
            return false;

        // Check if comparator is a Task object
        if (getClass() != obj.getClass())
        	return false;
        
        // Store comparator as Task object for comparison operations
        Task other = (Task) obj;

        // ID equality check
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;

        // name equality check
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;

        // description equality check
        if (description == null) {
            if (other.description != null)
                return false;
        } else if (!description.equals(other.description))
            return false;

        return true;
    }

    /**
     * Returns a string representation of the task.
     *
     * @return string in the format "Task(id=..., name=..., description=...)"
     */
    @Override
    public String toString() {
        return "Task(id=" + id + ", name=" + name + ", description=" + description + ")";
    }
}
