package appointmentService;

import java.util.Date;

/**
 * Appointment class for Java 1.8 compatibility.
 *
 * Stores appointment information including:
 *  - Appointment ID (unique, immutable)
 *  - Appointment Date
 *  - Description
 *
 * The appointment ID is generated by an external service and cannot be changed after creation.
 * All fields are immutable and final.
 */
public final class Appointment {
    private final String appointmentID;
    private final Date appointmentDate;
    private final String description;

    /**
     * Constructor for Appointment.
     *
     * @param appointmentID the unique appointment identifier
     * @param appointmentDate the appointment date
     * @param description the appointment description
     */
    public Appointment(String appointmentID, Date appointmentDate, String description) {
        this.appointmentID = appointmentID;
        this.appointmentDate = appointmentDate;
        this.description = description;
    }

    /**
     * Returns the appointment ID.
     *
     * @return the appointment ID
     */
    public String getAppointmentID() {
        return appointmentID;
    }

    /**
     * Returns the appointment date.
     *
     * @return the appointment date
     */
    public Date getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * Returns the appointment description.
     *
     * @return the appointment description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Compares this appointment with another object for equality.
     * Two appointments are equal if all their fields are equal.
     *
     * @param obj the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object obj) {
        // If comparator is null, default to false
        if (obj == null)
            return false;

        // Check if comparator is an Appointment object
        if (getClass() != obj.getClass())
            return false;

        // Store comparator as Appointment object for comparison operations
        Appointment other = (Appointment) obj;

        // Appointment ID equality check
        if (appointmentID == null) {
            if (other.appointmentID != null)
                return false;
        } else if (!appointmentID.equals(other.appointmentID))
            return false;

        // Appointment date equality check
        if (appointmentDate == null) {
            if (other.appointmentDate != null)
                return false;
        } else if (!appointmentDate.equals(other.appointmentDate))
            return false;

        // Description equality check
        if (description == null) {
            if (other.description != null)
                return false;
        } else if (!description.equals(other.description))
            return false;

        return true;
    }

    /**
     * Returns a string representation of the appointment.
     *
     * @return string in the format "Appointment(appointmentID=..., appointmentDate=..., description=...)"
     */
    @Override
    public String toString() {
        return "Appointment(appointmentID=" + appointmentID + ", appointmentDate=" + appointmentDate + ", description=" + description + ")";
    }
}